"""Numerical validation: Angrist replication datasets against R-generated fixtures.

External ground truth
---------------------
All benchmark values in this file come from JSON fixtures generated by R scripts
in scripts/r/, which are independent translations of Angrist's original Stata/SAS
replication code.  The fixture generation pipeline is:

    Angrist's Stata/SAS code
         ↓  translated to
    scripts/r/{paper}_fixtures.R   (R, using AER::ivreg + sandwich)
         ↓  executed by
    scripts/generate_fixtures.py
         ↓  produces
    tests/validation/fixtures/angrist/{paper}.json   ← loaded here

This means the tests genuinely verify that econtools output agrees with an
independent implementation (R), not just with itself.

To regenerate fixtures after data updates:
    python scripts/generate_fixtures.py --force

Papers covered
--------------
1. Angrist & Krueger (1991) — QJE  (doi:10.7910/DVN/ENLGZX)
   Dataset: asciiqob.tab  (N = 329,509; 1980 Census)
   R source: ak91.sas → scripts/r/ak91_fixtures.R

2. Angrist & Lavy (1999) — QJE  (doi:10.7910/DVN/XRSUJU)
   Datasets: final5.tab, final4.tab
   R source: AngristLavy_Table4.do → scripts/r/lavy99_fixtures.R

3. Angrist, Bettinger, Bloom, King & Kremer (2002) — AER  (doi:10.7910/DVN/K57TOZ)
   Dataset: aerdat4.tab  (N = 1,618 survey respondents)
   R source: table2_final.sas → scripts/r/vouchers02_fixtures.R

Tolerance policy
----------------
- Coefficients: ±0.5 % relative (R and Python use the same LAPACK routines for OLS/2SLS)
- Standard errors: ±2 % relative (small-sample correction choices differ between
  implementations; AER::ivreg default HC vs linearmodels default; cluster SE formulae)
- Sample sizes: exact integer match
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ANGRIST_DIR = (
    Path(__file__).resolve().parents[2]
    / "data_lake" / "raw" / "angrist_replication"
)
_FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "angrist"


def _tab(filename: str) -> Path:
    return _ANGRIST_DIR / filename


def _fixture(name: str) -> dict:
    path = _FIXTURE_DIR / f"{name}.json"
    if not path.exists():
        pytest.skip(
            f"Fixture {path.name} not found. "
            f"Run: python scripts/generate_fixtures.py --paper {name.split('_')[0]}"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def require_tab(filename: str) -> pytest.MarkDecorator:
    path = _tab(filename)
    return pytest.mark.skipif(
        not path.exists(),
        reason=f"data_lake/raw/angrist_replication/{filename} not present",
    )


# ---------------------------------------------------------------------------
# Tolerance helpers
# ---------------------------------------------------------------------------

def assert_coef_close(actual: float, expected: float, label: str, rtol: float = 0.005) -> None:
    """Assert coefficients agree within rtol (relative tolerance)."""
    if abs(expected) < 1e-9:
        assert abs(actual - expected) < 1e-4, (
            f"{label}: actual={actual:.6f} expected={expected:.6f} (near-zero, abs check)"
        )
    else:
        rel_err = abs(actual - expected) / abs(expected)
        assert rel_err <= rtol, (
            f"{label}: actual={actual:.6f} expected={expected:.6f} "
            f"relative error={rel_err:.4%} (limit {rtol:.1%})"
        )


def assert_se_close(actual: float, expected: float, label: str, rtol: float = 0.02) -> None:
    """Assert standard errors agree within rtol (2 % default — allows for small-sample correction differences)."""
    if abs(expected) < 1e-9:
        return
    rel_err = abs(actual - expected) / abs(expected)
    assert rel_err <= rtol, (
        f"{label} SE: actual={actual:.6f} expected={expected:.6f} "
        f"relative error={rel_err:.4%} (limit {rtol:.1%})"
    )


# ---------------------------------------------------------------------------
# AK91: Angrist & Krueger (1991)
# ---------------------------------------------------------------------------


@require_tab("asciiqob.tab")
def test_ak91_sample_integrity() -> None:
    """asciiqob.tab: 329,509 observations, correct columns, no missing values."""
    df = pd.read_csv(_tab("asciiqob.tab"), sep="\t")
    assert len(df) == 329_509
    assert list(df.columns) == [
        "log_weekly_wage", "education", "year_of_birth",
        "quarter_of_birth", "place_of_birth",
    ]
    assert df.isna().sum().sum() == 0
    assert set(df["year_of_birth"].unique()) == set(range(30, 40))
    assert df["quarter_of_birth"].between(1, 4).all()


@require_tab("asciiqob.tab")
def test_ak91_ols_vs_r_fixture() -> None:
    """AK91 OLS: lwklywge ~ yr21-yr29 + educ matches R/ak91.sas benchmark.

    R source: proc syslin, model lwklywge = yr21-yr29 educ
    Tolerance: ±0.5 % on coef, ±2 % on SE.
    """
    import statsmodels.api as sm

    fx = _fixture("ak91")["ols"]
    df = pd.read_csv(_tab("asciiqob.tab"), sep="\t")

    # Mirror R: yr21=(yob==31), ..., yr29=(yob==39); yr20=(yob==30) is reference
    for yr in range(21, 30):
        df[f"yr{yr}"] = (df["year_of_birth"] == yr + 10).astype(float)
    yr_cols = [f"yr{y}" for y in range(21, 30)]

    X = sm.add_constant(pd.concat([df[yr_cols], df[["education"]].astype(float)], axis=1))
    ols = sm.OLS(df["log_weekly_wage"].astype(float), X).fit()

    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["education"]), fx["educ_coef"], "AK91 OLS educ")
    assert_se_close(float(ols.bse["education"]), fx["educ_se"], "AK91 OLS educ")


@require_tab("asciiqob.tab")
def test_ak91_iv3_vs_r_fixture() -> None:
    """AK91 2SLS (3 QOB instruments): educ coef matches R/ak91.sas benchmark.

    R source: AER::ivreg, instruments = yr21-yr29 + qtr1 + qtr2 + qtr3
    Tolerance: ±0.5 % on coef, ±2 % on SE.
    """
    from econtools.models.iv import fit_iv_2sls

    fx = _fixture("ak91")["iv3"]
    df = pd.read_csv(_tab("asciiqob.tab"), sep="\t")

    for q in [1, 2, 3, 4]:
        df[f"q{q}"] = (df["quarter_of_birth"] == q).astype(float)
    for yr in range(21, 30):
        df[f"yr{yr}"] = (df["year_of_birth"] == yr + 10).astype(float)
    yr_cols = [f"yr{y}" for y in range(21, 30)]

    result = fit_iv_2sls(
        df,
        dep_var="log_weekly_wage",
        exog_vars=yr_cols,
        endog_vars=["education"],
        instruments=["q1", "q2", "q3"],
        add_constant=True,
    )

    assert result.fit.nobs == fx["nobs"]
    assert_coef_close(float(result.params["education"]), fx["educ_coef"], "AK91 2SLS-3 educ")
    assert_se_close(float(result.bse["education"]), fx["educ_se"], "AK91 2SLS-3 educ")


@require_tab("asciiqob.tab")
def test_ak91_iv_exceeds_ols() -> None:
    """AK91 canonical result: IV return to schooling exceeds OLS (LATE > ATE)."""
    fx = _fixture("ak91")
    assert fx["iv3"]["educ_coef"] > fx["ols"]["educ_coef"], (
        f"IV ({fx['iv3']['educ_coef']:.4f}) should exceed OLS ({fx['ols']['educ_coef']:.4f})"
    )


# ---------------------------------------------------------------------------
# Angrist & Lavy (1999)
# ---------------------------------------------------------------------------


def _load_lavy(grade: int) -> pd.DataFrame:
    df = pd.read_csv(_tab(f"final{grade}.tab"), sep="\t", quoting=3)
    df["avgverb"] = df["avgverb"].where(df["avgverb"] <= 100, df["avgverb"] - 100)
    df["avgmath"] = df["avgmath"].where(df["avgmath"] <= 100, df["avgmath"] - 100)
    df["func1"] = df["c_size"] / (((df["c_size"] - 1) / 40).astype(int) + 1)
    df.loc[df["verbsize"] == 0, "avgverb"] = np.nan
    df.loc[df["mathsize"] == 0, "avgmath"] = np.nan
    df.loc[df["verbsize"] == 0, "passverb"] = np.nan
    df.loc[df["mathsize"] == 0, "passmath"] = np.nan
    df = df[(df["classize"] > 1) & (df["classize"] < 45) & (df["c_size"] > 5)]
    df = df[(df["c_leom"] == 1) & (df["c_pik"] < 3)]
    # Table 4 additionally drops rows with missing avgverb (keep if avgverb~=.)
    df = df[~df["avgverb"].isna()]
    return df.copy()


@require_tab("final5.tab")
def test_lavy_grade5_sample_integrity() -> None:
    """AL99 grade-5 sample after Table 4 restrictions: matches R fixture N."""
    fx = _fixture("lavy99")["grade5"]
    df = _load_lavy(5)
    assert len(df) == fx["nobs_verbal"], (
        f"Grade 5 N = {len(df)}, expected {fx['nobs_verbal']}"
    )


@require_tab("final5.tab")
def test_lavy_grade5_ols_classize_no_controls_vs_r() -> None:
    """AL99 grade 5: OLS avgverb ~ classize (no controls) matches R fixture.

    Positive coefficient expected: larger classes correlate with better scores
    due to sorting (richer, urban schools have larger classes and higher scores).
    """
    import statsmodels.api as sm

    fx = _fixture("lavy99")["grade5"]["ols"]["verbal_no_controls"]
    df = _load_lavy(5)

    ols = sm.OLS(df["avgverb"].astype(float),
                 sm.add_constant(df[["classize"]].astype(float))).fit()
    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["classize"]), fx["coef"], "AL99 grade5 OLS no-controls")


@require_tab("final5.tab")
def test_lavy_grade5_ols_classize_with_controls_vs_r() -> None:
    """AL99 grade 5: OLS avgverb ~ classize + tipuach + c_size matches R fixture."""
    import statsmodels.api as sm

    fx = _fixture("lavy99")["grade5"]["ols"]["verbal_tipuach_csize"]
    df = _load_lavy(5)

    ols = sm.OLS(df["avgverb"].astype(float),
                 sm.add_constant(df[["classize", "tipuach", "c_size"]].astype(float))).fit()
    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["classize"]), fx["coef"], "AL99 grade5 OLS +controls")


@require_tab("final5.tab")
def test_lavy_grade5_iv_verbal_tipuach_csize_vs_r() -> None:
    """AL99 grade 5: IV avgverb ~ classize | func1 + tipuach + c_size matches R.

    R source: AngristLavy_Table4.do mmoulton avgverb (classize=func1) tipuach c_size
    Expected: classize ≈ -0.277 (s.e. ≈ 0.076).
    """
    from econtools.models.iv import fit_iv_2sls

    fx = _fixture("lavy99")["grade5"]["iv"]["verbal_tipuach_csize"]
    df = _load_lavy(5)

    result = fit_iv_2sls(
        df,
        dep_var="avgverb",
        exog_vars=["tipuach", "c_size"],
        endog_vars=["classize"],
        instruments=["func1"],
        add_constant=True,
    )

    assert result.fit.nobs == fx["nobs"]
    assert_coef_close(float(result.params["classize"]), fx["coef"], "AL99 grade5 IV verbal", rtol=0.005)


@require_tab("final5.tab")
def test_lavy_grade5_iv_math_tipuach_csize_vs_r() -> None:
    """AL99 grade 5: IV avgmath ~ classize | func1 + tipuach + c_size matches R.

    Expected: classize ≈ -0.231 (s.e. ≈ 0.099).
    """
    from econtools.models.iv import fit_iv_2sls

    fx = _fixture("lavy99")["grade5"]["iv"]["math_tipuach_csize"]
    df = _load_lavy(5)
    dm = df.dropna(subset=["avgmath"]).copy()

    result = fit_iv_2sls(
        dm,
        dep_var="avgmath",
        exog_vars=["tipuach", "c_size"],
        endog_vars=["classize"],
        instruments=["func1"],
        add_constant=True,
    )

    assert result.fit.nobs == fx["nobs"]
    assert_coef_close(float(result.params["classize"]), fx["coef"], "AL99 grade5 IV math", rtol=0.005)


@require_tab("final4.tab")
def test_lavy_grade4_iv_verbal_vs_r() -> None:
    """AL99 grade 4: IV avgverb ~ classize | func1 + tipuach + c_size matches R."""
    from econtools.models.iv import fit_iv_2sls

    fx = _fixture("lavy99")["grade4"]["iv"]["verbal_tipuach_csize"]
    df = _load_lavy(4)

    result = fit_iv_2sls(
        df,
        dep_var="avgverb",
        exog_vars=["tipuach", "c_size"],
        endog_vars=["classize"],
        instruments=["func1"],
        add_constant=True,
    )

    assert result.fit.nobs == fx["nobs"]
    assert_coef_close(float(result.params["classize"]), fx["coef"], "AL99 grade4 IV verbal", rtol=0.005)


@require_tab("final5.tab")
def test_lavy_sorting_bias_sign_flip() -> None:
    """AL99 key result: OLS positive (sorting bias) flips to negative IV (causal).

    Both directions confirmed against R benchmarks.
    """
    fx = _fixture("lavy99")["grade5"]
    ols_coef = fx["ols"]["verbal_no_controls"]["coef"]
    iv_coef  = fx["iv"]["verbal_tipuach_csize"]["coef"]
    assert ols_coef > 0, f"OLS should be positive (sorting bias): {ols_coef:.4f}"
    assert iv_coef  < 0, f"IV should be negative (causal effect): {iv_coef:.4f}"


# ---------------------------------------------------------------------------
# Angrist et al. (2002) — Colombia Vouchers
# ---------------------------------------------------------------------------


def _survey_sample(df: pd.DataFrame) -> pd.DataFrame:
    mask = (
        df["bog95smp"].fillna(0).astype(bool)
        | df["bog97smp"].fillna(0).astype(bool)
        | df["jam93smp"].fillna(0).astype(bool)
    )
    return df[mask].copy()


def _panel_c_controls(df: pd.DataFrame) -> list[str]:
    """Return Panel C controls matching R's vouchers02_fixtures.R specification.

    R's lm() aliases seven columns as perfectly collinear (structural duplicates):
      - dbogota  = 1 - djamundi  (every obs is from exactly one city)
      - d1993    = djamundi      (all 1993 survey obs are from Jamundi)
      - d1997    = 1 - d1995 - djamundi  (linear combo of kept cols)
      - dmonth12 = reference month (sum of month dummies = 1 for all survey obs)
      - darea2, darea3, darea13  = all-zero in the survey sample
    We exclude these to ensure statsmodels uses the same rank-33 model as R.
    Column order follows the dataframe (R's grep order), not sorted alphabetically.
    """
    area_cols  = [c for c in df.columns if c.startswith("darea")]
    month_cols = [c for c in df.columns if c.startswith("dmonth")]
    base = ["vouch0", "svy", "hsvisit", "djamundi", "d1995"]
    month_keep = [c for c in month_cols if c != "dmonth12"]
    area_keep  = [c for c in area_cols if c in df.columns and df[c].std() > 0]
    return base + month_keep + area_keep


@require_tab("aerdat4.tab")
def test_vouchers_survey_sample_size() -> None:
    """Colombia vouchers survey sample: exact N matches R fixture."""
    fx = _fixture("vouchers02")
    df = pd.read_csv(_tab("aerdat4.tab"), sep="\t")
    svy = _survey_sample(df)
    assert len(svy) == fx["survey_sample_n"], (
        f"Survey N = {len(svy)}, expected {fx['survey_sample_n']}"
    )


@require_tab("aerdat4.tab")
def test_vouchers_balance_phone_vs_r() -> None:
    """Colombia vouchers Table 3 Panel C: phone ~ vouch0 matches R/SAS benchmark.

    R source: table3_final.sas proc reg; model phone = vouch0 ... /acov
    Expected: vouch0 ≈ 0.020 (small — confirms lottery randomisation).
    """
    import statsmodels.api as sm

    fx = _fixture("vouchers02")["panel_c"]["phone"]
    df = pd.read_csv(_tab("aerdat4.tab"), sep="\t")
    svy = _survey_sample(df)
    controls = _panel_c_controls(svy)

    d = svy.dropna(subset=["phone"] + controls)
    X = sm.add_constant(d[controls].astype(float))
    ols = sm.OLS(d["phone"].astype(float), X).fit(cov_type="HC0")

    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["vouch0"]), fx["coef"], "Vouchers phone~vouch0")
    assert_se_close(float(ols.bse["vouch0"]), fx["se"], "Vouchers phone~vouch0 SE")


@require_tab("aerdat4.tab")
def test_vouchers_scyfnsh_vs_r() -> None:
    """Colombia vouchers: scyfnsh ~ vouch0 (years of schooling) matches R/SAS.

    Expected: vouch0 ≈ 0.102 — vouchers raised school completion by ~0.1 years.
    """
    import statsmodels.api as sm

    fx = _fixture("vouchers02")["panel_c"]["scyfnsh"]
    df = pd.read_csv(_tab("aerdat4.tab"), sep="\t")
    svy = _survey_sample(df)
    controls = _panel_c_controls(svy)

    d = svy.dropna(subset=["scyfnsh"] + controls)
    X = sm.add_constant(d[controls].astype(float))
    ols = sm.OLS(d["scyfnsh"].astype(float), X).fit(cov_type="HC0")

    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["vouch0"]), fx["coef"], "Vouchers scyfnsh~vouch0")


@require_tab("aerdat4.tab")
def test_vouchers_private_school_vs_r() -> None:
    """Colombia vouchers: prscha_1 ~ vouch0 (private school year 1) matches R.

    Positive coefficient confirms compliance: voucher winners attended private schools.
    """
    import statsmodels.api as sm

    fx = _fixture("vouchers02")["panel_c"]["prscha_1"]
    df = pd.read_csv(_tab("aerdat4.tab"), sep="\t")
    svy = _survey_sample(df)
    controls = _panel_c_controls(svy)

    d = svy.dropna(subset=["prscha_1"] + controls)
    X = sm.add_constant(d[controls].astype(float))
    ols = sm.OLS(d["prscha_1"].astype(float), X).fit(cov_type="HC0")

    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["vouch0"]), fx["coef"], "Vouchers prscha_1~vouch0")
    assert ols.params["vouch0"] > 0, "Voucher effect on private schooling should be positive"


@require_tab("aerdat4.tab")
def test_vouchers_totscyrs_vs_r() -> None:
    """Colombia vouchers: totscyrs ~ vouch0 (total schooling years) matches R."""
    import statsmodels.api as sm

    fx = _fixture("vouchers02")["panel_c"]["totscyrs"]
    df = pd.read_csv(_tab("aerdat4.tab"), sep="\t")
    svy = _survey_sample(df)
    controls = _panel_c_controls(svy)

    d = svy.dropna(subset=["totscyrs"] + controls)
    X = sm.add_constant(d[controls].astype(float))
    ols = sm.OLS(d["totscyrs"].astype(float), X).fit(cov_type="HC0")

    assert int(ols.nobs) == fx["nobs"]
    assert_coef_close(float(ols.params["vouch0"]), fx["coef"], "Vouchers totscyrs~vouch0")


# ---------------------------------------------------------------------------
# Fixture provenance checks (meta-tests)
# ---------------------------------------------------------------------------


def test_fixtures_have_provenance() -> None:
    """All fixture files should record R version, package versions, and generator."""
    for name in ["ak91", "lavy99", "vouchers02"]:
        fx = _fixture(name)
        assert "r_version" in fx, f"{name}.json missing r_version"
        assert "generator" in fx, f"{name}.json missing generator"
        assert "source_doi" in fx, f"{name}.json missing source_doi"


def test_fixture_ak91_exact_nobs() -> None:
    """AK91 fixture: nobs must equal 329,509 (canonical census extract)."""
    fx = _fixture("ak91")
    assert fx["ols"]["nobs"] == 329_509
    assert fx["iv3"]["nobs"] == 329_509
    assert fx["iv30"]["nobs"] == 329_509
