"""Generate external ground-truth fixtures for Angrist replication tests.

Runs each R script in scripts/r/ against the raw Dataverse data to produce
JSON fixture files in tests/validation/fixtures/angrist/.  Fixtures are the
authoritative external benchmark: they are generated by R (not by econtools),
so the validation tests genuinely test that our Python implementation matches
independent R output rather than testing self-consistency.

R equivalence notes
-------------------
- ``AER::ivreg`` uses the same two-stage algebra as Stata's ``ivreg``/``ivreg2``;
  results agree to ≥ 6 significant figures for standard IV specs.
- ``sandwich::vcovCL`` matches Stata's ``vce(cluster)``; small differences may
  arise from the finite-sample correction (Stata default: G/(G-1)*(N-1)/(N-K),
  R default: G/(G-1)).  We therefore allow ±1 % tolerance on SEs in tests.
- ``sandwich::vcovHC(type="HC0")`` matches SAS ``proc reg /acov`` exactly.

Usage
-----
    # Generate all fixtures (run once, commit the JSON files):
    python scripts/generate_fixtures.py

    # Force regeneration even if fixtures are up to date:
    python scripts/generate_fixtures.py --force

    # Only regenerate a specific paper:
    python scripts/generate_fixtures.py --paper ak91

    # Use a non-default Rscript path:
    python scripts/generate_fixtures.py --rscript "C:/Program Files/R/R-4.5.1/bin/Rscript.exe"
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys
from datetime import datetime, timezone

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
_SCRIPTS_R = _REPO_ROOT / "scripts" / "r"
_FIXTURE_DIR = _REPO_ROOT / "tests" / "validation" / "fixtures" / "angrist"
_DATA_DIR = _REPO_ROOT / "data_lake" / "raw" / "angrist_replication"

# Default Rscript locations to probe (Windows-first ordering)
_RSCRIPT_CANDIDATES = [
    r"C:\Program Files\R\R-4.5.1\bin\Rscript.exe",
    r"C:\Program Files\R\R-4.5.0\bin\Rscript.exe",
    "Rscript",          # on PATH
    "/usr/bin/Rscript",
    "/usr/local/bin/Rscript",
]

# Registry: paper_key -> (r_script, required_data_files, fixture_output, extra_r_args)
_PAPERS: dict[str, dict] = {
    "ak91": {
        "script": "ak91_fixtures.R",
        "requires": ["asciiqob.tab"],
        "fixture": "ak91.json",
        "extra_args": [],
    },
    "lavy99": {
        "script": "lavy99_fixtures.R",
        "requires": ["final5.tab", "final4.tab"],
        "fixture": "lavy99.json",
        "extra_args": ["--data-dir", str(_DATA_DIR)],
    },
    "vouchers02": {
        "script": "vouchers02_fixtures.R",
        "requires": ["aerdat4.tab"],
        "fixture": "vouchers02.json",
        "extra_args": [],
    },
}


def _find_rscript(override: str | None) -> str:
    if override:
        return override
    for candidate in _RSCRIPT_CANDIDATES:
        if pathlib.Path(candidate).exists():
            return candidate
    # Try PATH
    which = subprocess.run(
        ["where", "Rscript"] if sys.platform == "win32" else ["which", "Rscript"],
        capture_output=True,
        text=True,
    )
    if which.returncode == 0:
        return which.stdout.strip().splitlines()[0]
    raise RuntimeError(
        "Rscript not found. Install R (https://cran.r-project.org/) or pass "
        "--rscript /path/to/Rscript."
    )


def _fixture_is_stale(fixture_path: pathlib.Path, data_paths: list[pathlib.Path]) -> bool:
    """Return True if the fixture doesn't exist or is older than any data file."""
    if not fixture_path.exists():
        return True
    fixture_mtime = fixture_path.stat().st_mtime
    for dp in data_paths:
        if dp.exists() and dp.stat().st_mtime > fixture_mtime:
            return True
    return False


def run_paper(
    key: str,
    rscript: str,
    force: bool,
) -> tuple[bool, str]:
    """Generate fixture for one paper.  Returns (success, message)."""
    spec = _PAPERS[key]

    # Check required data files
    data_paths = [_DATA_DIR / f for f in spec["requires"]]
    missing = [p for p in data_paths if not p.exists()]
    if missing:
        return False, f"SKIP  {key}: data file(s) missing: {[p.name for p in missing]}"

    fixture_path = _FIXTURE_DIR / spec["fixture"]

    if not force and not _fixture_is_stale(fixture_path, data_paths):
        return True, f"UP-TO-DATE  {key}: {fixture_path.name}"

    # Build the R command
    r_script_path = _SCRIPTS_R / spec["script"]
    cmd = [
        rscript,
        str(r_script_path),
        "--data", str(_DATA_DIR / spec["requires"][0]),
        "--out",  str(fixture_path),
    ] + spec["extra_args"]

    print(f"  Running R: {r_script_path.name} ...", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"  STDERR:\n{result.stderr}", file=sys.stderr)
        return False, f"FAIL  {key}: R script exited with code {result.returncode}"

    # Print R's progress output
    for line in result.stderr.strip().splitlines():
        print(f"    {line}")

    # Annotate the fixture with generation metadata
    if fixture_path.exists():
        try:
            data = json.loads(fixture_path.read_text(encoding="utf-8"))
            data["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
            data["generated_by"] = "scripts/generate_fixtures.py"
            fixture_path.write_text(
                json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
            )
        except Exception:
            pass  # don't fail on annotation errors

    return True, f"OK    {key}: {fixture_path.name}"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--paper",
        choices=list(_PAPERS),
        help="Only regenerate this paper's fixture (default: all)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate even if fixture is already up to date",
    )
    parser.add_argument(
        "--rscript",
        metavar="PATH",
        help="Path to Rscript executable",
    )
    args = parser.parse_args()

    try:
        rscript = _find_rscript(args.rscript)
        print(f"Using Rscript: {rscript}")
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    # Verify R can load AER
    check = subprocess.run(
        [rscript, "-e", "library(AER); library(sandwich); library(jsonlite); cat('OK')"],
        capture_output=True, text=True,
    )
    if "OK" not in check.stdout:
        print("ERROR: R is missing required packages (AER, sandwich, jsonlite).", file=sys.stderr)
        print("  Run in R:  install.packages(c('AER', 'sandwich', 'jsonlite'))", file=sys.stderr)
        return 1
    print(f"R package check: AER + sandwich + jsonlite OK\n")

    _FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    papers_to_run = [args.paper] if args.paper else list(_PAPERS)
    results: list[tuple[bool, str]] = []

    for key in papers_to_run:
        ok, msg = run_paper(key, rscript, args.force)
        results.append((ok, msg))
        status = "OK" if ok else "FAIL"
        print(f"  [{status}] {msg}")

    failed = [msg for ok, msg in results if not ok]
    print(f"\n{len(results) - len(failed)}/{len(results)} fixture(s) generated successfully.")
    if failed:
        print("\nFailed or skipped:")
        for msg in failed:
            print(f"  {msg}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
